### ISSUE TITLE
Zoro.to CSS Style 

### ISSUE THREAD

**Issue by pandahacker** [Adaptz/Adaptz.github.io#1]
Comments under the video player are not visible while the stylesheet is enabled.

![image](https://github.com/Adaptz/Adaptz.github.io/assets/2483918/5521f914-d531-4f15-8dc8-e26337ac9c2e)

![image](https://github.com/Adaptz/Adaptz.github.io/assets/2483918/3b6606de-e589-43fb-8be2-f09a6f29c3c4)

**Comment by Adaptz** [comment]
Should be fixed now, they changed a few tiny things when they rebranded.

**Comment by pandahacker** [comment]
Appreciate it thanks!
